/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['voxel_map_level1-4-0_1']: THREE.Mesh
    ['voxel_map_level1-4-0_2']: THREE.Mesh
    ['voxel_map_level1-4-0_3']: THREE.Mesh
    ['voxel_map_level1-4-0_4']: THREE.Mesh
    ['voxel_map_level1-4-0_5']: THREE.Mesh
    ['voxel_map_level1-4-0_6']: THREE.Mesh
    ['voxel_map_level1-4-0_7']: THREE.Mesh
    ['voxel_map_level1-4-0_8']: THREE.Mesh
  }
  materials: {
    ['floor-wall']: THREE.MeshBasicMaterial
    ['drop-box']: THREE.MeshBasicMaterial
    ['auth-box']: THREE.MeshBasicMaterial
    ['box-base-grey']: THREE.MeshBasicMaterial
    ['box-base-orange']: THREE.MeshBasicMaterial
    box: THREE.MeshBasicMaterial
    ['auth-button']: THREE.MeshBasicMaterial
    ['auth-text']: THREE.MeshBasicMaterial
  }
}

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('models/level3.glb') as GLTFResult
  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      name='world'
      position={[300, 0, 80]}
      rotation={[0, 4.4, 0]}
    >
      <mesh
        geometry={nodes['voxel_map_level1-4-0_1'].geometry}
        material={materials['floor-wall']}
      />
      <mesh
        geometry={nodes['voxel_map_level1-4-0_2'].geometry}
        material={materials['drop-box']}
        // onDrop
      />
      <mesh
        geometry={nodes['voxel_map_level1-4-0_3'].geometry}
        material={materials['auth-box']}
      />
      <mesh
        geometry={nodes['voxel_map_level1-4-0_4'].geometry}
        material={materials['box-base-grey']}
      />
      <mesh
        geometry={nodes['voxel_map_level1-4-0_5'].geometry}
        material={materials['box-base-orange']}
      />
      <mesh
        geometry={nodes['voxel_map_level1-4-0_6'].geometry}
        material={materials.box}
      />
      <mesh
        geometry={nodes['voxel_map_level1-4-0_7'].geometry}
        material={materials['auth-button']}
        onClick={() => {
          console.log('auth button clicked')
        }}
      />
      <mesh
        geometry={nodes['voxel_map_level1-4-0_8'].geometry}
        material={materials['auth-text']}
      />
    </group>
  )
}

useGLTF.preload('/level3.glb')
