/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'
import BillBoard from '@/components/billboard'

type GLTFResult = GLTF & {
  nodes: {
    ['palace_voxel_final-2']: THREE.Mesh
    ['palace_voxel_final-2_1']: THREE.Mesh
    ['palace_voxel_final-2_2']: THREE.Mesh
  }
  materials: {
    ['palace_voxel_final-2 #249']: THREE.MeshBasicMaterial
    ['palace_voxel_final-2 #242']: THREE.MeshBasicMaterial
    ['palace_voxel_final-2 #250']: THREE.MeshBasicMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF(
    'models/world/mid/palace-thanks.glb'
  ) as GLTFResult
  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      position={[58, 0, -67]}
      rotation={[0, Math.PI / 2, 0]}
      name='palace-bottom-right'
    >
      <mesh
        geometry={nodes['palace_voxel_final-2'].geometry}
        material={materials['palace_voxel_final-2 #249']}
        name='palace-bottom-right'
      />
      <mesh
        geometry={nodes['palace_voxel_final-2_1'].geometry}
        material={materials['palace_voxel_final-2 #242']}
        name='palace-bottom-right'
      />
      <mesh
        geometry={nodes['palace_voxel_final-2_2'].geometry}
        material={materials['palace_voxel_final-2 #250']}
        name='palace-bottom-right'
      />

      <BillBoard position={[-95, -10, -60]}>NFT of the Day </BillBoard>
    </group>
  )
}

// useGLTF.preload('models/world/mid/palace-thanks.glb')
