/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    ['palace_voxel_final-3']: THREE.Mesh
    ['palace_voxel_final-3_1']: THREE.Mesh
    ['palace_voxel_final-3_2']: THREE.Mesh
  }
  materials: {
    ['palace_voxel_final-3 #249']: THREE.MeshBasicMaterial
    ['palace_voxel_final-3 #250']: THREE.MeshBasicMaterial
    ['palace_voxel_final-3 #242']: THREE.MeshBasicMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF(
    'models/world/mid/palace_table.glb'
  ) as GLTFResult
  return (
    <group ref={group} {...props} dispose={null} name='palace-bottom-left'>
      <group position={[58, 0, 89]} rotation={[0, Math.PI / 2, 0]}>
        <mesh
          geometry={nodes['palace_voxel_final-3'].geometry}
          material={materials['palace_voxel_final-3 #249']}
          name='palace-bottom-left'
        />
        <mesh
          geometry={nodes['palace_voxel_final-3_1'].geometry}
          material={materials['palace_voxel_final-3 #250']}
          name='palace-bottom-left'
        />
        <mesh
          geometry={nodes['palace_voxel_final-3_2'].geometry}
          material={materials['palace_voxel_final-3 #242']}
          name='palace-bottom-left'
        />
      </group>
    </group>
  )
}

// useGLTF.preload('models/world/mid/palace_table.glb')
