/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    ['world_export-13_1']: THREE.Mesh
    ['world_export-13_2']: THREE.Mesh
    ['world_export-13_3']: THREE.Mesh
  }
  materials: {
    ['world_export-13 #1']: THREE.MeshStandardMaterial
    ['world_export-13 #246']: THREE.MeshStandardMaterial
    ['world_export-13 #254']: THREE.MeshStandardMaterial
  }
}

export default function MidBottomLeft(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF(
    'models/world/mid/mid_bottom_left.glb'
  ) as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[58.27, 0, 89.1]} rotation={[0, Math.PI / 2, 0]}>
        <mesh
          geometry={nodes['world_export-13_1'].geometry}
          material={materials['world_export-13 #1']}
        />
        <mesh
          geometry={nodes['world_export-13_2'].geometry}
          material={materials['world_export-13 #246']}
        />
        <mesh
          geometry={nodes['world_export-13_3'].geometry}
          material={materials['world_export-13 #254']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('models/world/mid/mid_bottom_left.glb')
