/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    ['world_export-16_1']: THREE.Mesh
    ['world_export-16_2']: THREE.Mesh
    ['world_export-16_3']: THREE.Mesh
  }
  materials: {
    ['world_export-16 #1']: THREE.MeshStandardMaterial
    ['world_export-16 #246']: THREE.MeshStandardMaterial
    ['world_export-16 #254']: THREE.MeshStandardMaterial
  }
}

export default function MidTopLeft(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF(
    '/models/world/mid/mid_top_left.glb'
  ) as GLTFResult
  return (
    <group ref={group} {...props} dispose={null} name='palace-top-left'>
      <group position={[-98, 0, 89]} rotation={[0, Math.PI / 2, 0]}>
        <mesh
          geometry={nodes['world_export-16_1'].geometry}
          material={materials['world_export-16 #1']}
          name='palace-top-left'
        />
        <mesh
          geometry={nodes['world_export-16_2'].geometry}
          material={materials['world_export-16 #246']}
          name='palace-top-left'
        />
        <mesh
          geometry={nodes['world_export-16_3'].geometry}
          material={materials['world_export-16 #254']}
          name='palace-top-left'
        />
      </group>
    </group>
  )
}

useGLTF.preload('models/world/mid/mid_top_left.glb')
