/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    ['palace_voxel_final-0']: THREE.Mesh
    ['palace_voxel_final-0_1']: THREE.Mesh
    ['palace_voxel_final-0_2']: THREE.Mesh
  }
  materials: {
    ['palace_voxel_final-0 #249']: THREE.MeshBasicMaterial
    ['palace_voxel_final-0 #250']: THREE.MeshBasicMaterial
    ['palace_voxel_final-0 #242']: THREE.MeshBasicMaterial
  }
}

export default function MidTopLeft(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF(
    '/models/world/mid/palace-rock.glb'
  ) as GLTFResult
  return (
    <group ref={group} {...props} dispose={null} name='palace-top-left'>
      <group position={[-98, 0, 89]} rotation={[0, Math.PI / 2, 0]}>
        <mesh
          geometry={nodes['palace_voxel_final-0'].geometry}
          material={materials['palace_voxel_final-0 #249']}
          name='palace-top-left'
        />
        <mesh
          geometry={nodes['palace_voxel_final-0_1'].geometry}
          material={materials['palace_voxel_final-0 #250']}
          name='palace-top-left'
        />
        <mesh
          geometry={nodes['palace_voxel_final-0_2'].geometry}
          material={materials['palace_voxel_final-0 #242']}
          name='palace-top-left'
        />
      </group>
    </group>
  )
}

// useGLTF.preload('models/world/mid/palace-rock.glb')
