/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    ['more_nfts_voxel-5']: THREE.Mesh
    ['more_nfts_voxel-5_1']: THREE.Mesh
  }
  materials: {
    ['more_nfts_voxel-5 #249']: THREE.MeshBasicMaterial
    ['more_nfts_voxel-5 #242']: THREE.MeshBasicMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/castle_entry_right.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 100, 0]}>
        <mesh geometry={nodes['more_nfts_voxel-5'].geometry} material={materials['more_nfts_voxel-5 #249']} />
        <mesh geometry={nodes['more_nfts_voxel-5_1'].geometry} material={materials['more_nfts_voxel-5 #242']} />
      </group>
    </group>
  )
}

useGLTF.preload('/castle_entry_right.glb')
