/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    ['more_nfts_voxel-1']: THREE.Mesh
    ['more_nfts_voxel-1_1']: THREE.Mesh
  }
  materials: {
    ['more_nfts_voxel-1 #249']: THREE.MeshBasicMaterial
    ['more_nfts_voxel-1 #242']: THREE.MeshBasicMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/throne-right.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 0, 202.83]} scale={[1, 1, -1]}>
        <mesh geometry={nodes['more_nfts_voxel-1'].geometry} material={materials['more_nfts_voxel-1 #249']} />
        <mesh geometry={nodes['more_nfts_voxel-1_1'].geometry} material={materials['more_nfts_voxel-1 #242']} />
      </group>
    </group>
  )
}

useGLTF.preload('/throne-right.glb')
