/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

// import * as THREE from 'three'
// import React, { useRef, useEffect, useState } from 'react'
// import { useGLTF } from '@react-three/drei'
// import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'
// import { ethers } from 'ethers'
// import Web3Modal from 'web3modal'
// import { nftAddress, nftMarketAddress } from '@/nftConfig'
// import NFT from '@/artifacts/contracts/NFT.sol/NFT.json'
// import Market from '@/artifacts/contracts/NFTMarket.sol/NFTMarket.json'
// import axios from 'axios'
// import NFTComp from '@/components/nft'

// type GLTFResult = GLTF & {
//   nodes: {
//     ['world_export-10_1']: THREE.Mesh
//     ['world_export-10_2']: THREE.Mesh
//   }
//   materials: {
//     ['world_export-10 #1']: THREE.MeshStandardMaterial
//     ['world_export-10 #254']: THREE.MeshStandardMaterial
//   }
// }

// export default function UserBottomRight(props: JSX.IntrinsicElements['group']) {
//   const group = useRef<THREE.Group>()
//   const { nodes, materials } = useGLTF(
//     'models/world/user/user_bottom_right.glb'
//   ) as GLTFResult

//   const [nfts, setNfts] = useState([])
//   const [sold, setSold] = useState([])
//   const [loadingState, setLoadingState] = useState('not-loaded')

//   useEffect(() => {
//     loadNFTs()
//   }, [])

//   async function loadNFTs() {
//     const web3Modal = new Web3Modal()

//     const connection = await web3Modal.connect()
//     const provider = new ethers.providers.Web3Provider(connection)
//     const signer = provider.getSigner()

//     const marketContract = new ethers.Contract(
//       nftMarketAddress,
//       Market.abi,
//       signer
//     )
//     const tokenContract = new ethers.Contract(nftAddress, NFT.abi, provider)
//     const data = await marketContract.fetchItemsCreated()

//     const items = await Promise.all(
//       data.map(async (i) => {
//         const tokenUri = await tokenContract.tokenURI(i.tokenId)

//         // console.log(tokenUri)
//         const meta = await axios.get(tokenUri).catch((err) => {
//           // console.log('get model axios err', err)
//         })

//         // console.log(meta)

//         let price = ethers.utils.formatUnits(i.price.toString(), 'ether')

//         let item = {
//           price,
//           tokenId: i.tokenId.toNumber(),
//           seller: i.seller,
//           owner: i.owner,
//           sold: i.sold,
//           image: meta?.data?.image,
//         }

//         return item
//       })
//     )

//     console.log(items, 'user bottom right')

//     // filtering NFts with no image
//     const filteredItems = items.filter((i) => i.image)
//     console.log(filteredItems)

//     /* create a filtered array of items that have been sold */
//     const soldItems = filteredItems.filter((i) => i.sold)
//     setSold(soldItems)
//     setNfts(filteredItems)
//     setLoadingState('loaded')
//   }

//   const nftPositions = [
//     [-100, -62, 270],
//     [-80, -62, 270],
//     [-60, -62, 270],
//     [-100, -62, 320],
//     [-80, -62, 320],
//     [-60, -62, 320],
//     [-100, -62, 220],
//     [-80, -62, 220],
//     [-60, -62, 220],
//   ]

//   return (
//     <group ref={group} {...props} dispose={null}>
//       <group position={[-97.34, 0, 245.49]} rotation={[-Math.PI, 0, -Math.PI]}>
//         <mesh
//           geometry={nodes['world_export-10_1'].geometry}
//           material={materials['world_export-10 #1']}
//         />
//         <mesh
//           geometry={nodes['world_export-10_2'].geometry}
//           material={materials['world_export-10 #254']}
//         />
//       </group>

//       {loadingState === 'loaded' && nfts
//         ? nfts.map((el, i) => {
//             return (
//               <NFTComp
//                 position={nftPositions[i]}
//                 key={i}
//                 {...el}
//                 onClick={() => {
//                   console.log('clicked', el)
//                 }}
//               />
//             )
//           })
//         : null}

//       {/* <mesh position={[-100, -62, 270]} scale={[6, 6, 6]}>
//         <boxGeometry args={[1, 1, 1]} />
//         <meshStandardMaterial color={'hotpink'} />
//       </mesh>
//       <mesh position={[-80, -62, 270]} scale={[6, 6, 6]}>
//         <boxGeometry args={[1, 1, 1]} />
//         <meshStandardMaterial color={'hotpink'} />
//       </mesh>
//       <mesh position={[-60, -62, 270]} scale={[6, 6, 6]}>
//         <boxGeometry args={[1, 1, 1]} />
//         <meshStandardMaterial color={'hotpink'} />
//       </mesh>
//       <mesh position={[-100, -62, 320]} scale={[6, 6, 6]}>
//         <boxGeometry args={[1, 1, 1]} />
//         <meshStandardMaterial color={'hotpink'} />
//       </mesh>
//       <mesh position={[-80, -62, 320]} scale={[6, 6, 6]}>
//         <boxGeometry args={[1, 1, 1]} />
//         <meshStandardMaterial color={'hotpink'} />
//       </mesh>
//       <mesh position={[-60, -62, 320]} scale={[6, 6, 6]}>
//         <boxGeometry args={[1, 1, 1]} />
//         <meshStandardMaterial color={'hotpink'} />
//       </mesh>
//       <mesh position={[-100, -62, 220]} scale={[6, 6, 6]}>
//         <boxGeometry args={[1, 1, 1]} />
//         <meshStandardMaterial color={'hotpink'} />
//       </mesh>
//       <mesh position={[-80, -62, 220]} scale={[6, 6, 6]}>
//         <boxGeometry args={[1, 1, 1]} />
//         <meshStandardMaterial color={'hotpink'} />
//       </mesh>
//       <mesh position={[-60, -62, 220]} scale={[6, 6, 6]}>
//         <boxGeometry args={[1, 1, 1]} />
//         <meshStandardMaterial color={'hotpink'} />
//       </mesh> */}
//     </group>
//   )
// }

// useGLTF.preload('models/world/user/user_bottom_right.glb')

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    ['user_voxel-bottom-0']: THREE.Mesh
    ['user_voxel-bottom-0_1']: THREE.Mesh
  }
  materials: {
    ['user_voxel-bottom-0 #249']: THREE.MeshBasicMaterial
    ['user_voxel-bottom-0 #242']: THREE.MeshBasicMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('models/world/user/user_bottom_portal.glb') as GLTFResult
  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      position={[-97, 0, 245]}
      rotation={[-Math.PI, 0, -Math.PI]}
      name="user-portal"
    >
      <mesh
        geometry={nodes['user_voxel-bottom-0'].geometry}
        material={materials['user_voxel-bottom-0 #249']}
      />
      <mesh
        geometry={nodes['user_voxel-bottom-0_1'].geometry}
        material={materials['user_voxel-bottom-0 #242']}
      />
    </group>
  )
}

useGLTF.preload('models/world/user/user_bottom_portal.glb')
