/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    ['world_export-9']: THREE.Mesh
  }
  materials: {
    ['world_export-9 #1']: THREE.MeshStandardMaterial
  }
}

export default function UserBottomLeft(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF(
    'models/world/user/user_bottom_left.glb'
  ) as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes['world_export-9'].geometry}
        material={materials['world_export-9 #1']}
        position={[58.53, 0, 246.09]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
    </group>
  )
}

useGLTF.preload('models/world/user/user_bottom_left.glb')
