/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    ['world_export-12_1']: THREE.Mesh
    ['world_export-12_2']: THREE.Mesh
  }
  materials: {
    ['world_export-12 #1']: THREE.MeshStandardMaterial
    ['world_export-12 #254']: THREE.MeshStandardMaterial
  }
}

export default function UserTopRight(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('models/world/user/user_top_right.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-97.14, 0, 400.9]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh geometry={nodes['world_export-12_1'].geometry} material={materials['world_export-12 #1']} />
        <mesh geometry={nodes['world_export-12_2'].geometry} material={materials['world_export-12 #254']} />
      </group>
    </group>
  )
}

useGLTF.preload('models/world/user/user_top_right.glb')
