/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

import { ethers } from 'ethers'
import { useEffect, useState } from 'react'
import axios from 'axios'
import Web3Modal from 'web3modal'

import { nftMarketAddress, nftAddress } from '@/nftConfig'

import NFT from '@/artifacts/contracts/NFT.sol/NFT.json'
import Market from '@/artifacts/contracts/NFTMarket.sol/NFTMarket.json'

import NFTComp from '@/components/nft'
import useLoad from '@/store/load'
import BillBoard from '@/components/billboard'

type GLTFResult = GLTF & {
  nodes: {
    user_bottom_entry: THREE.Mesh
  }
  materials: {
    ['user_voxel-bottom-1 #249']: THREE.MeshBasicMaterial
  }
}

export default function UserBottomLeft(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF(
    'models/world/user/user_bottom_enter_com.glb'
  ) as GLTFResult

  const load = useLoad(({ chunkData }) => chunkData('user-enter').load)
  if (!load) return null

  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      position={[59, 0, 245]}
      rotation={[-Math.PI, 0, -Math.PI]}
      name='user-enter'
    >
      <group>
        <mesh
          geometry={nodes.user_bottom_entry.geometry}
          material={materials['user_voxel-bottom-1 #249']}
          name='user-enter'
        />

        {/* <mesh
          geometry={nodes['user_voxel-bottom-1'].geometry}
          material={materials['user_voxel-bottom-1 #249']}
          name='user-enter'
        />
        <mesh
          geometry={nodes['user_voxel-bottom-1_1'].geometry}
          material={materials['user_voxel-bottom-1 #242']}
          name='user-enter'
        /> */}

        <BillBoard position={[-40, -60, 40]}>Welcome to your Garden</BillBoard>

        <BillBoard position={[10, -70, -40]}>
          See the NFTs that you have published on the market
        </BillBoard>
      </group>
    </group>
  )
}
