/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    ['world_export-6_1']: THREE.Mesh
    ['world_export-6_2']: THREE.Mesh
    ['world_export-6_3']: THREE.Mesh
  }
  materials: {
    ['world_export-6 #1']: THREE.MeshStandardMaterial
    ['world_export-6 #173']: THREE.MeshStandardMaterial
    ['world_export-6 #254']: THREE.MeshStandardMaterial
  }
}

export default function CastleEnterRight(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('models/world/castle/castle_enter_right.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-254.39, 0, -66.57]}>
        <mesh geometry={nodes['world_export-6_1'].geometry} material={materials['world_export-6 #1']} />
        <mesh geometry={nodes['world_export-6_2'].geometry} material={materials['world_export-6 #173']} />
        <mesh geometry={nodes['world_export-6_3'].geometry} material={materials['world_export-6 #254']} />
      </group>
    </group>
  )
}

useGLTF.preload('models/world/castle/castle_enter_right.glb')
