/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'
import useLoad from '@/store/load'

type GLTFResult = GLTF & {
  nodes: {
    ['throne-left']: THREE.Mesh
  }
  materials: {
    ['more_nfts_voxel-1 #249']: THREE.MeshBasicMaterial
  }
}

export default function CastlePillorThroneLeft(
  props: JSX.IntrinsicElements['group']
) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF(
    'models/world/castle/throne-left.glb'
  ) as GLTFResult

  const load = useLoad(({ chunkData }) => chunkData('throne-left').load)
  if (!load) return null

  return (
    <group ref={group} {...props} dispose={null} name='throne-left'>
      <group position={[-722, 0, 91.8]}>
        {/* <mesh
          name='throne-left'
          geometry={nodes['throne-left'].geometry}
          material={materials['more_nfts_voxel-1 #249']}
        /> */}

        <mesh
          name='throne-left'
          geometry={nodes['more_nfts_voxel-1'].geometry}
          material={materials['more_nfts_voxel-1 #249']}
        />

        {/* <mesh
          geometry={nodes['more_nfts_voxel-1'].geometry}
          material={materials['more_nfts_voxel-1 #249']}
          name='throne-left'
        />
        <mesh
          geometry={nodes['more_nfts_voxel-1_1'].geometry}
          material={materials['more_nfts_voxel-1 #242']}
          name='throne-left'
        /> */}
      </group>
    </group>
  )
}

// useGLTF.preload('models/world/castle/throne-left.glb')
