/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    ['user_voxel-bottom-0']: THREE.Mesh
    ['user_voxel-bottom-0_1']: THREE.Mesh
  }
  materials: {
    ['user_voxel-bottom-0 #249']: THREE.MeshBasicMaterial
    ['user_voxel-bottom-0 #242']: THREE.MeshBasicMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/user_bottom_portal.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes['user_voxel-bottom-0'].geometry} material={materials['user_voxel-bottom-0 #249']} />
      <mesh geometry={nodes['user_voxel-bottom-0_1'].geometry} material={materials['user_voxel-bottom-0 #242']} />
    </group>
  )
}

useGLTF.preload('/user_bottom_portal.glb')
