/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    user_upload_1: THREE.Mesh
    user_upload_2: THREE.Mesh
    user_upload_3: THREE.Mesh
  }
  materials: {
    ['user_upload #255']: THREE.MeshBasicMaterial
    ['user_upload #249']: THREE.MeshBasicMaterial
    ['user_upload #242']: THREE.MeshBasicMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/user_water_upload.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.user_upload_1.geometry} material={materials['user_upload #255']} />
      <mesh geometry={nodes.user_upload_2.geometry} material={materials['user_upload #249']} />
      <mesh geometry={nodes.user_upload_3.geometry} material={materials['user_upload #242']} />
    </group>
  )
}

useGLTF.preload('/user_water_upload.glb')
