/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    ['user_voxel-bottom-1']: THREE.Mesh
    ['user_voxel-bottom-1_1']: THREE.Mesh
  }
  materials: {
    ['user_voxel-bottom-1 #249']: THREE.MeshBasicMaterial
    ['user_voxel-bottom-1 #242']: THREE.MeshBasicMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/user_bottom_enter.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-156.17, 0, 0]}>
        <mesh geometry={nodes['user_voxel-bottom-1'].geometry} material={materials['user_voxel-bottom-1 #249']} />
        <mesh geometry={nodes['user_voxel-bottom-1_1'].geometry} material={materials['user_voxel-bottom-1 #242']} />
      </group>
    </group>
  )
}

useGLTF.preload('/user_bottom_enter.glb')
