/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    test1_level009: THREE.Mesh
    test1_level009_1: THREE.Mesh
    test1_level009_2: THREE.Mesh
    test1_level009_3: THREE.Mesh
    test1_level009_4: THREE.Mesh
    test1_level009_5: THREE.Mesh
    test1_level009_6: THREE.Mesh
    test1_level009_7: THREE.Mesh
  }
  materials: {
    ['test1_level #253']: THREE.MeshBasicMaterial
    ['test1_level #252']: THREE.MeshBasicMaterial
    ['test1_level #251']: THREE.MeshBasicMaterial
    ['test1_level #1']: THREE.MeshBasicMaterial
    ['test1_level #255']: THREE.MeshBasicMaterial
    ['test1_level #254']: THREE.MeshBasicMaterial
    ['test1_level #246']: THREE.MeshBasicMaterial
    ['test1_level #77']: THREE.MeshBasicMaterial
  }
}

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('models/map1-new.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null} name='world'>
      <group position={[0, 0, 0]}>
        <mesh
          geometry={nodes.test1_level009.geometry}
          material={materials['test1_level #253']}
        />
        <mesh
          geometry={nodes.test1_level009_1.geometry}
          material={materials['test1_level #252']}
        />
        <mesh
          geometry={nodes.test1_level009_2.geometry}
          material={materials['test1_level #251']}
        />
        <mesh
          geometry={nodes.test1_level009_3.geometry}
          material={materials['test1_level #1']}
        />
        <mesh
          geometry={nodes.test1_level009_4.geometry}
          material={materials['test1_level #255']}
        />
        <mesh
          geometry={nodes.test1_level009_5.geometry}
          material={materials['test1_level #254']}
        />
        <mesh
          geometry={nodes.test1_level009_6.geometry}
          material={materials['test1_level #246']}
        />
        <mesh
          geometry={nodes.test1_level009_7.geometry}
          material={materials['test1_level #77']}
        />
      </group>
    </group>
  )
}

// useGLTF.preload('/map1-new.glb')
